name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Building
        run: bazel build //...
      - name: Testing
        run: bazel test //...
